import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/contexts/AuthContext'
import { X, AlertCircle, ArrowUpCircle, Sparkles } from 'lucide-react'

interface PromoteOffspringFormProps {
    offspring: {
        id: string
        id_anakan: string
        gender: 'jantan' | 'betina' | null
        birth_date: string
        generation: number
        weight_kg: number | null
        health_status: string | null
        mother_id: string
        father_id: string | null
        kandang_id: string | null
    }
    onClose: () => void
    onSuccess: () => void
}

interface Breed {
    id: string
    breed_code: string
    breed_name: string
}

interface Kandang {
    id: string
    kandang_code: string
    name: string
}

export function PromoteOffspringForm({ offspring, onClose, onSuccess }: PromoteOffspringFormProps) {
    const { user } = useAuth()
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState('')
    const [motherBreed, setMotherBreed] = useState<Breed | null>(null)
    const [kandangList, setKandangList] = useState<Kandang[]>([])
    const [generatedCode, setGeneratedCode] = useState<string | null>(null)
    const [formData, setFormData] = useState({
        kandang_id: '', // Don't transfer from offspring - cage will be changed
        notes: `Dipromosikan dari anakan ${offspring.id_anakan}`,
    })

    useEffect(() => {
        fetchMotherBreed()
        fetchKandang()
    }, [])

    // Fetch mother's breed to use for the new livestock
    const fetchMotherBreed = async () => {
        if (!offspring.mother_id) return

        const { data } = await supabase
            .from('livestock')
            .select(`
                breed_id,
                settings_breeds (
                    id,
                    breed_code,
                    breed_name
                )
            `)
            .eq('id', offspring.mother_id)
            .single()

        if (data && data.settings_breeds) {
            setMotherBreed(data.settings_breeds as unknown as Breed)
        }
    }

    const fetchKandang = async () => {
        const { data } = await supabase
            .from('kandang')
            .select('id, kandang_code, name')
            .order('kandang_code')
        setKandangList((data as Kandang[]) || [])
    }

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()
        setError('')
        setLoading(true)

        if (!motherBreed) {
            setError('Tidak dapat menemukan ras dari induk. Pastikan data induk lengkap.')
            setLoading(false)
            return
        }

        try {
            // Create new livestock record - id_indukan will be auto-generated by database trigger
            // @ts-ignore - Supabase types limitation
            const { data: insertedData, error: insertError } = await supabase
                .from('livestock')
                .insert({
                    user_id: user?.id,
                    // id_indukan will be auto-generated by trigger based on breed_id + gender
                    breed_id: motherBreed.id,
                    gender: offspring.gender,
                    birth_date: offspring.birth_date,
                    generation: offspring.generation,
                    weight_kg: offspring.weight_kg,
                    kandang_id: formData.kandang_id || null,
                    mother_id: offspring.mother_id,
                    father_id: offspring.father_id || null,
                    status: 'aktif',
                    status_farm: 'infarm',
                    health_status: offspring.health_status || 'sehat',
                    acquisition_source: 'farm_breeding',
                    acquisition_date: new Date().toISOString().split('T')[0],
                    notes: formData.notes,
                } as any)
                .select('id, id_indukan')
                .single()

            if (insertError) throw insertError

            const newLivestockId = (insertedData as any)?.id
            const newLivestockCode = (insertedData as any)?.id_indukan || 'N/A'
            setGeneratedCode(newLivestockCode)

            // Transfer all health records from offspring to livestock
            const { data: healthRecords } = await supabase
                .from('offspring_health_records')
                .select('*')
                .eq('offspring_id', offspring.id)

            if (healthRecords && healthRecords.length > 0) {
                const livestockHealthRecords = healthRecords.map((record: any) => ({
                    livestock_id: newLivestockId,
                    record_date: record.record_date,
                    record_type: record.record_type,
                    description: record.description,
                    treatment: record.treatment,
                    cost: record.cost,
                    user_id: user?.id,
                }))

                const { error: healthError } = await supabase
                    .from('livestock_health_records')
                    .insert(livestockHealthRecords as any)

                if (healthError) {
                    console.error('Error transferring health records:', healthError)
                }
            }

            // Transfer all growth logs from offspring to livestock
            const { data: growthLogs } = await supabase
                .from('offspring_growth_logs')
                .select('*')
                .eq('offspring_id', offspring.id)

            if (growthLogs && growthLogs.length > 0) {
                const livestockGrowthLogs = growthLogs.map((log: any) => ({
                    livestock_id: newLivestockId,
                    measurement_date: log.measurement_date,
                    weight_kg: log.weight_kg,
                    notes: log.notes,
                    user_id: user?.id,
                }))

                const { error: growthError } = await supabase
                    .from('livestock_growth_logs')
                    .insert(livestockGrowthLogs as any)

                if (growthError) {
                    console.error('Error transferring growth logs:', growthError)
                }
            }

            // Update offspring status to 'promosi'
            const updatePayload: any = {
                status_farm: 'promosi',
                status_notes: `Dipromosikan menjadi indukan dengan kode ${newLivestockCode}`
            }
            // @ts-ignore - Supabase types limitation
            const { error: updateError } = await supabase
                .from('offspring')
                .update(updatePayload)
                .eq('id', offspring.id)

            if (updateError) throw updateError

            onSuccess()
            onClose()
        } catch (err: any) {
            setError(err.message)
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={onClose}>
            <div className="bg-white rounded-xl shadow-xl max-w-md w-full" onClick={(e) => e.stopPropagation()}>
                <div className="flex justify-between items-center p-6 border-b bg-gradient-to-r from-purple-500 to-purple-600">
                    <div className="flex items-center gap-3">
                        <ArrowUpCircle className="h-6 w-6 text-white" />
                        <h2 className="text-xl font-bold text-white">Promosi ke Indukan</h2>
                    </div>
                    <button onClick={onClose} className="text-white/80 hover:text-white">
                        <X className="h-6 w-6" />
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="p-6">
                    {error && (
                        <div className="mb-4 bg-red-50 border border-red-200 text-red-800 rounded-lg p-3 flex items-start gap-2">
                            <AlertCircle className="h-5 w-5 flex-shrink-0 mt-0.5" />
                            <p className="text-sm">{error}</p>
                        </div>
                    )}

                    {/* Info box showing offspring data that will be transferred */}
                    <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 mb-4">
                        <h4 className="font-semibold text-purple-800 mb-2 flex items-center gap-2">
                            <Sparkles className="h-4 w-4" />
                            Data Anakan yang Akan Ditransfer
                        </h4>
                        <div className="grid grid-cols-2 gap-2 text-sm text-purple-700">
                            <div><strong>ID Anakan:</strong> {offspring.id_anakan}</div>
                            <div><strong>Gender:</strong> {offspring.gender === 'jantan' ? '♂ Jantan' : '♀ Betina'}</div>
                            <div><strong>Generasi:</strong> Gen {offspring.generation}</div>
                            <div><strong>Berat:</strong> {offspring.weight_kg ? `${offspring.weight_kg} kg` : '-'}</div>
                            <div><strong>Tanggal Lahir:</strong> {new Date(offspring.birth_date).toLocaleDateString('id-ID')}</div>
                            <div><strong>Kesehatan:</strong> {offspring.health_status || 'sehat'}</div>
                        </div>
                    </div>

                    {/* Auto-detected breed info */}
                    <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
                        <p className="text-sm text-blue-800">
                            <strong>Ras (dari Induk):</strong>{' '}
                            {motherBreed ? `${motherBreed.breed_name} (${motherBreed.breed_code})` : 'Memuat...'}
                        </p>
                        <p className="text-xs text-blue-600 mt-1">
                            ID Indukan akan di-generate otomatis berdasarkan ras dan jenis kelamin.
                        </p>
                    </div>

                    <div className="space-y-4">
                        {/* Kandang selection */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Kandang</label>
                            <select
                                value={formData.kandang_id}
                                onChange={(e) => setFormData({ ...formData, kandang_id: e.target.value })}
                                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                            >
                                <option value="">Pilih Kandang</option>
                                {kandangList.map((k) => (
                                    <option key={k.id} value={k.id}>
                                        {k.kandang_code} - {k.name}
                                    </option>
                                ))}
                            </select>
                        </div>

                        {/* Notes */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Catatan</label>
                            <textarea
                                rows={2}
                                value={formData.notes}
                                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                            />
                        </div>
                    </div>

                    <div className="flex gap-3 mt-6">
                        <button
                            type="button"
                            onClick={onClose}
                            className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
                        >
                            Batal
                        </button>
                        <button
                            type="submit"
                            disabled={loading || !motherBreed}
                            className="flex-1 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50"
                        >
                            {loading ? 'Memproses...' : 'Promosi ke Indukan'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    )
}
